services:

  # Generate TLS certificates
  # ------------------------------
  #
  generate-tls:
    user: 1000:1000
    build:
      context: .
      dockerfile: generate-tls.Dockerfile
    volumes:
      - ./:/app

  # Traefik
  # ------------------------------
  #
  traefik:
    image: traefik:v3.1
    container_name: traefik-tls
    user: 1000:1000
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .tls:/tls
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./config/traefik/dynamic-configurations:/dynamic-configurations
