networks:
  traefikNet:
    name: traefikNet
    attachable: true

services:
  # Traefik
  # ------------------------------
  #
  traefik:
    image: traefik:v3.1
    container_name: traefik-tls
    user: 1000:1000
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefikNet
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .tls:/tls
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./config/traefik/dynamic-configurations:/dynamic-configurations

  # Nginx
  # ------------------------------
  #
  nginx:
    image: nginx:latest
    container_name: nginx
    expose:
      - "80"
      - "443"
    networks:
      - traefikNet
    volumes:
      - ./config/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - .tls:/tls