http:
  routers:
    localhost:
      rule: "Host(`localhost`)"
      service: localhost
      tls: { }
      entryPoints:
        - websecure
      priority: 1
  serversTransports:
    nginxTransport:
      serverName: "localhost"
      rootCAs:
        - /tls/intermediate/certs/intermediate.cert.pem
  services:
    localhost:
      loadBalancer:
        serversTransport: "nginxTransport"
        servers:
          - url: "https://nginx:443"